# action.yml
name: "Deploy to ELB"
description: "Deploys to all servers behind an ELB using remove SSH execution."
inputs:
  script: # id of input
    description: "Script to execute on each remote server"
    required: true
    default: "/home/ubuntu/deploy_ci.sh"
  autoscaling_group_name: # id of input
    description: Autoscaling group to deploy to
    required: true
    default: maheshstacker-AutoScalingGroup-eP8d1668oMgA
  ssh_key: # id of input
    description: Private SSH key to use to authenticate with the server"
    required: true
    default: ${{secrets.SSH_PEM}}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.script }}
    - ${{ inputs.autoscaling_group_name }}
    - ${{ inputs.ssh_key }}
branding:
  icon: 'activity'
  color: 'blue'
