name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ELB
        uses: maheshsubramanian52/deploy-to-elb-action-mah@main
        with:
          script: /home/ubuntu/deploy_ci.sh
          autoscaling_group_name: ${{ secrets.AUTOSCALING_GROUP_NAME }}
          ssh_key: ${{ secrets.SSH_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
